<query>         ::= <select> [<where>] [<order>] [<show>]
                  | <insert> <values> [<associate>]
                  | <update> <where> <set> <associate> | <update> <where> <set> | <update> <where> <associate>
                  | <delete> [<where>]
                  | <undelete> [<where>]
                  | <describe>
                  ;


; Query types
<select>        ::= "SELECT" <locationgraph> ;
<insert>        ::= "INSERT" <locationgraph> ;
<update>        ::= "UPDATE" <entityname> ;
<delete>        ::= "DELETE" <entityname> ;
<undelete>      ::= "UNDELETE" <entityname> ;
<describe>      ::= "DESCRIBE" <entityname> ;


; LOCATION GRAPH
<locationgraph> ::= <entityname>":[" <locationgraphi> "]" ;

<locationgraphi>::= <entityname>":[" <locationgraphi> "]" ["," <locationgraphi>]
                  | <entityname> ["," <locationgraphi>]
                  | <locationagg> ["," <locationgraphi>]
                  | <namespacecount> ["," <locationgraphi>]
                  ;

<locationagg>   ::= <aggfuncname>"(" <location> ")" ;
<namespacecount>::= <countfuncname>"(" <namespace> ")" ;


; WHERE
<where>         ::= WHERE <wheres> ;

<wheres>        ::= <wherecompare> ["AND" <wheres>] ;

<wherecompare>  ::= <namespace>":(" <colaggcomps> ")" ;

<colaggcomps>   ::= <colaggcomp> ["AND" <colaggcomps>];

<colaggcomp>    ::= ["HAS"] <entityname> <comparison> <value>
                  | <entityname> "IN" <parameter>
                  | <colagg> <comparison> <value>
                  ;

<colagg>        ::= <aggfuncname>"(" <entityname ")" ;
<schemacount>   ::= <countfuncname"(" <entityname> ")" ;


; VALUES
<values>        ::= VALUES <valuegraphs> ;

<valuegraphs>   ::= <entityname>":[" <valuegraph> "]" ;

<valuegraph>    ::= <entityname>":[" <valuegraph> "]" ["," <valuegraph>]
                  | <value> ["," <valuegraph>]
                  ;


; SET
<set>           ::= SET <sets> ;

<sets>          ::= <colassign> ["," <sets>] ;

<colassign>     ::= <entityname> <assign> <value> ;


// ASSOCIATE
<associate>     ::= "ASSOCIATE" "WITH" <associates> ;

<associates>    ::= <colexpr> ["," <associates>] ;

<colexpr>       ::= <column> <comparison> <value> ;


; ORDER
<order>         ::= "ORDER" <orders> ;

<orders>        ::= <orderby> ["," <orders>] ;

<orderby>       ::= <namespace> "BY" <entityname> <orderoptions> ;

<orderoptions>  ::= "ASC" | "DESC" ;


; SHOW
<show>          ::= "SHOW" <shows> ;

<shows>         ::= <showrp> ["," <showrs>] ;

<showrs>        ::= <showr> ["," <showrs>] ;

<showrp>        ::= <showr> ["PAGE" <posinteger>] ;

<showr>         ::= <posinteger> <namespace> ;


; Columns, locations, and namespaces

<location>      ::= <namespace>":"<entityname> ;

<column>        ::= <entityname>":"<entityname> ;

<namespace>     ::= <entityname>["."<namespace>] ;


; Low level
<entityname>    ::= "`"<objectname>"`" | <objectname> ;

<value>         ::= <constant> | <parameter> ;

<parameter>     ::= "?"<alphanum> ;

<constant>      ::= <double> | <integer> | <string> | <boolean> ;


; Operators
<comparison>    ::= "==" | "!=" | "<" | "<=" | ">" | ">=" ;
<assign>        ::= "=" ;


; Function names
<aggfuncname>   ::= "SUM" | "AVERAGE" | "MEAN" | "MEDIAN" | "MIN" | "MAX" ;
<countfuncname> ::= "COUNT" ;


; Tokens
<objectname>    ::= ^([0-9a-zA-Z$_]+)(?=[\s`,.\)\]]) ;
<alphanum>      ::= ^([a-zA-Z0-9]+)(?=[\s`,.\)\]]) ;
<integer>       ::= ^([-]?\d+)(?=[\s`,.\)\]]) ;
<posinteger>    ::= ^([1-9]+[0-9]*)(?=[\s`,.\)\]]) ;
<double>        ::= ^([-]?[0-9]*\.?[0-9]+)(?=[\s`,.\)\]]) ;
<string>        ::= ^(L?\"(\\.|[^\\"])*\")(?=[\s`,.\)\]]) ;
<boolean>       ::= "true" | "false" ;
